[package]
name = "simple_smtp_relay"
version = "0.0.1"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5.0"
anyhow = "1.0"

[dependencies.uuid]
version = "1.4.1"
features = [ "v4", "fast-rng" ]
